apiVersion: 1.0.0
logging:
    level:
        com:
            assignment:
                springboot:
                    mongo: DEBUG
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
        
publishStubMessage: http://10.0.5.35:30925/rest/message

server:
    port: 9011
    
serviceOrderManagementServiceURL: http://10.0.5.35:30928/serviceOrderManagement/v1/serviceOrder

spring:      
   data:
        mongodb:
            database: BMP_SERVICEORDERMANAGEMENT
            host: 10.0.5.36
            port: 27017    
   application:
      name: bmp-service-order-management-business-service  
   
eureka:         
  instance:   
    home-page-url: http://10.0.5.35:30928/      
    health-check-url: http://10.0.5.35:30928/health
    prefer-ip-address: true
    ip-address: 10.0.5.35    
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
    non-secure-port: 30928
    non-secure-port-enabled: true    
  client:
    serviceUrl:
      defaultZone: http://10.0.5.10:8761/eureka/
      enabled: true         
    register-with-eureka: true
endpoints:
  actuator:
    enabled: true    
management:
  port: 30928
  info:
    env:
      enabled: true   
    defaults: 
      enabled: true
  security:
     enabled: false 
        
